language: cpp

dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test # For newer GCC
    - george-edison55-precise-backports # For cmake
    - llvm-toolchain-trusty-7
    packages:
    - autoconf
    - automake
    - bash
    - bison
    - build-essential
    - cmake
    - ctags
    - curl
    - doxygen
    - flex
    - fontconfig
    - gcc-6
    - g++-6
    - gcc-4.9
    - gdb
    - git
    - gperf
    - libcairo2-dev
    - libevent-dev
    - libfontconfig1-dev
    - liblist-moreutils-perl
    - libncurses5-dev
    - libx11-dev
    - libxft-dev
    - libxml++2.6-dev
    - perl
    - python
    - texinfo
    - time
    - valgrind
    - zip
    - qt5-default
    - clang-format-7

before_install:
  - source ./.github/travis/common.sh

install:
  - ./.github/travis/install.sh

script:
  - ./.github/travis/script.sh

after_failure:
  - ./.github/travis/after_failure.sh

after_success:
  - ./.github/travis/after_success.sh
